apiVersion: v1
kind: Service
metadata:
  name: php-myadmin
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - name: http
      port: 8080
      targetPort: 80
      nodePort: 30000 # Change this to the desired port number
# spec:
#   ports:
#     - port: 80
#   selector:
#     app: phpmyadmin
#     tier: mysql
#   clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          env:
            - name: PMA_HOST
              value: wordpress-mysql
            - name: PMA_USER
              value: root
              # valueFrom:
              #   secretKeyRef:
              #     name: mysql-secrets
              #     key: username
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: root_password
            # - name: PMA_ROOT_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mysql-secrets
            #       key: root_password
          ports:
            - containerPort: 80
